/**
 * P1.2 — write TABLE_LABELS and PAGE_VIEWS into each company's Actions file
 * from tools/liveviews/inventory.json (the P0 output), between markers, so a
 * rerun replaces the block rather than adding another.
 *
 * Tables are written as the file's own sheet constants where one exists
 * (PRODUCTS_SHEET), else as the literal sheet name. The Testing System's
 * Actions file is generated from Top Light, so its block is written to
 * tools/erptest/live_views.inc.js and tools/erptest/gen_actions.js swaps it in.
 *
 * Run: node tools/liveviews/gen_page_views.js   (then node tools/erptest/gen_actions.js)
 * Local files only.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { scanActions } = require('./inventory');

const ROOT = path.resolve(__dirname, '..', '..');
const INV = JSON.parse(fs.readFileSync(path.join(__dirname, 'inventory.json'), 'utf8'));
const BEGIN = '  /* [live-notice] PAGE_VIEWS:begin — generated by tools/liveviews/gen_page_views.js from tools/liveviews/inventory.json; edit there. */';
const END = '  /* [live-notice] PAGE_VIEWS:end */';

function q(s) { return "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'"; }

function blockFor(company) {
  const known = scanActions(company);
  const byValue = {};
  Object.keys(known.sheetConsts).forEach(k => {
    const v = known.sheetConsts[k];
    /* Prefer a *_SHEET name, then the shortest. */
    if (!byValue[v] || (/_SHEET$/.test(k) && !/_SHEET$/.test(byValue[v])) || (/_SHEET$/.test(k) === /_SHEET$/.test(byValue[v]) && k.length < byValue[v].length)) byValue[v] = k;
  });
  /* A constant declared AFTER the block would be in its temporal dead zone
   * when the block runs at load, so only constants declared before it are used. */
  const src = fs.readFileSync(path.join(ROOT, 'Company_' + company + '_Actions.js'), 'utf8');
  const anchor = src.indexOf('const PAGE_TABLES = (function () {');
  const declaredBefore = k => { const at = src.search(new RegExp('\\b(?:const|var|let)\\s+' + k + '\\s*=')); return at !== -1 && at < anchor; };
  const ref = t => (byValue[t] && declaredBefore(byValue[t])) ? byValue[t] : q(t);
  const c = INV.companies[company];
  const labels = INV.labels[company];
  const used = new Set();
  Object.keys(c.pageViews).forEach(p => Object.keys(c.pageViews[p]).forEach(v => c.pageViews[p][v].forEach(t => used.add(t))));
  c.pages.forEach(p => p.pageTables.forEach(t => used.add(t)));
  const lines = [BEGIN];
  lines.push('  /**');
  lines.push('   * [live-notice D2] What each VIEW of a page shows: every table whose data is');
  lines.push('   * visible there, including tables that only supply a name, a total or an');
  lines.push('   * available quantity. The reason for each table is in tools/liveviews/inventory.md.');
  lines.push('   * get_page_versions watches PAGE_TABLES ∪ these, and tells the page which view');
  lines.push('   * each moved table belongs to, so a change off-screen does not interrupt.');
  lines.push('   */');
  lines.push('  const TABLE_LABELS = (function () {');
  lines.push('    const o = {};');
  [...used].sort().forEach(t => {
    if (!labels[t]) return;
    lines.push('    o[' + ref(t) + '] = ' + q(labels[t].label) + ';');
  });
  lines.push('    return o;');
  lines.push('  })();');
  lines.push('  const PAGE_VIEWS = {');
  const pages = Object.keys(c.pageViews);
  pages.forEach((p, i) => {
    const views = c.pageViews[p];
    const vk = Object.keys(views);
    lines.push('    ' + q(p) + ': {');
    vk.forEach((v, j) => {
      lines.push('      ' + q(v) + ': [' + views[v].map(ref).join(', ') + ']' + (j < vk.length - 1 ? ',' : ''));
    });
    lines.push('    }' + (i < pages.length - 1 ? ',' : ''));
  });
  lines.push('  };');
  lines.push(END);
  return lines.join('\n');
}

function writeInto(file, block) {
  const p = path.join(ROOT, file);
  let s = fs.readFileSync(p, 'utf8');
  const b = s.indexOf(BEGIN.split(' — ')[0]);
  if (b !== -1) {
    const e = s.indexOf(END, b);
    if (e === -1) throw new Error(file + ': PAGE_VIEWS:end marker missing');
    s = s.slice(0, b) + block + s.slice(e + END.length);
  } else {
    /* First run: right after the PAGE_TABLES IIFE. */
    const at = s.indexOf('const PAGE_TABLES = (function () {');
    if (at === -1) throw new Error(file + ': PAGE_TABLES not found');
    const close = s.indexOf('\n  })();', at);
    if (close === -1) throw new Error(file + ': PAGE_TABLES close not found');
    const insertAt = close + '\n  })();'.length;
    s = s.slice(0, insertAt) + '\n\n' + block + s.slice(insertAt);
  }
  fs.writeFileSync(p, s, 'utf8');
}

['TopLight', 'TopChemical', 'ValleyFoods', 'Assessment'].forEach(c => {
  writeInto('Company_' + c + '_Actions.js', blockFor(c));
  console.log('wrote PAGE_VIEWS/TABLE_LABELS into Company_' + c + '_Actions.js');
});
fs.writeFileSync(path.join(ROOT, 'tools', 'erptest', 'live_views.inc.js'), blockFor('ErpTest') + '\n', 'utf8');
console.log('wrote tools/erptest/live_views.inc.js (swapped in by tools/erptest/gen_actions.js)');
module.exports = { BEGIN, END };
