/** Repository boundary for system data; company code keeps using Sheet helpers. */
function isSystemTableBackend_(dbId, tableName) { return String(dbId || '') === String(CONFIG.AUTH_SPREADSHEET_ID || '') && isSystemTable_(tableName); }
function systemLegacyRecord_(r) { var out = {}; Object.keys(r.data || {}).forEach(function (k) { out[String(k).trim().toLowerCase()] = r.data[k]; }); try { Object.defineProperty(out, '_meta', { value: r.meta, enumerable: false }); } catch (e) { out._meta = r.meta; } return out; }
function systemRecordData_(r) { var out = {}; Object.keys(r || {}).forEach(function (k) { if (k !== '_meta') out[k] = r[k]; }); return out; }
function systemGetAllRecords_(table, options) { return systemStore_().queryAll(table, options || {}).records.map(systemLegacyRecord_); }
function systemFindByBusinessKey_(table, field, value, options) { var r = systemStore_().query(table, { filters: [{ field: field, value: value, op: 'EQUAL' }], limit: 2 }); if (r.records.length > 1 && !(options && options.allowMultiple)) throw new Error('STORAGE_INTEGRITY_ERROR: duplicate ' + table + '.' + field); return r.records.length ? systemLegacyRecord_(r.records[0]) : null; }
function systemFindByFields_(table, filters, options) { var r = systemStore_().query(table, { filters: (filters || []).map(function (f) { return { field: f.field, value: f.value, op: f.op || 'EQUAL' }; }), limit: (options && options.limit) || 2 }); if (r.records.length > 1 && !(options && options.allowMultiple)) throw new Error('STORAGE_INTEGRITY_ERROR: duplicate query for ' + table); return r.records.length ? systemLegacyRecord_(r.records[0]) : null; }
function systemPatchByFields_(table, filters, changes, options) { var found = systemFindByFields_(table, filters, options); if (!found) throw new Error('STORAGE_NOT_FOUND: ' + table); return systemPatchRecord_(table, found._meta.documentId, changes, Object.assign({}, options || {}, { expectedUpdateTime: options && options.expectedUpdateTime || found._meta.updateTime })); }
function systemCreateRecord_(table, data, options) { return systemStore_().create(table, data, options || {}); }
function systemAddRecordCompat_(table, data, requiredFields) {
  var missing = (requiredFields || []).filter(function (f) { return data[f] === undefined || data[f] === null || String(data[f]).trim() === ''; });
  if (missing.length) throw new Error('Missing required fields: ' + missing.join(', '));
  var payload = Object.assign({}, data);
  if (payload.id === undefined && systemSchema_(table).keys.indexOf('id') === -1) {
    var wantsId = table === 'ERP_Users' || table === 'ERP_Companies' || table === 'ERP_currency_exchange' || table === 'ERP_User_Views';
    if (wantsId) payload.id = systemNextNumericId_(table, 'id');
  }
  var operationId = payload.unique_id || payload.event_id || payload.email || Utilities.getUuid();
  var created = systemCreateRecord_(table, payload, { operationId: operationId });
  var record = systemLegacyRecord_(created);
  return { status: 'success', message: 'Record added successfully', data: { record: record, newRowNumber: null, assignedId: payload.id } };
}
function systemPatchRecord_(table, id, changes, options) { return systemStore_().patch(table, id, changes, options || {}); }
function systemRemoveRecord_(table, id, options) { return systemStore_().remove(table, id, options || {}); }
function systemPatchByBusinessKey_(table, field, value, changes, options) { var found = systemFindByBusinessKey_(table, field, value, options); if (!found) throw new Error('STORAGE_NOT_FOUND: ' + table + '.' + field); return systemPatchRecord_(table, found._meta.documentId, changes, Object.assign({}, options || {}, { expectedUpdateTime: options && options.expectedUpdateTime || found._meta.updateTime })); }
function systemRemoveByBusinessKey_(table, field, value, options) { var found = systemFindByBusinessKey_(table, field, value, options); if (!found) return false; return systemRemoveRecord_(table, found._meta.documentId, Object.assign({}, options || {}, { expectedUpdateTime: options && options.expectedUpdateTime || found._meta.updateTime })); }
function systemFindFlagRecord_() { var rows = systemStore_().queryAll('ERP_system_work', {}).records.filter(function (r) { return Object.prototype.hasOwnProperty.call(r.data || {}, 'on_off'); }); if (rows.length > 1) throw new Error('STORAGE_INTEGRITY_ERROR: multiple ERP_system_work flag documents'); return rows.length ? rows[0] : null; }
function systemNextNumericId_(table, field) { var rows = systemStore_().queryAll(table, {}).records, max = 0; rows.forEach(function (r) { var n = Number(r.data[field]); if (isFinite(n) && Math.floor(n) === n && n > max) max = n; }); return max + 1; }
function systemStore_() { var c = systemStorageTarget_(); return c.backend === 'sheets' ? sheetsStore_() : firestoreStore_(c); }
function getAllRecordsFromSheets_(dbId, table) { var sheet = getSheet_(table, dbId), headers = getHeaders_(sheet), rows = buildRecordsFromRaw_(sheet.getDataRange().getValues(), headers); rows.forEach(function (r, i) { try { Object.defineProperty(r, '_meta', { value: { documentId: String(i + 2), updateTime: '' }, enumerable: false }); } catch (e) { r._meta = { documentId: String(i + 2), updateTime: '' }; } }); return rows; }
function sheetsStore_() { return { query: function (table, options) { var rows = getAllRecordsFromSheets_(CONFIG.AUTH_SPREADSHEET_ID, table), fs = (options && options.filters) || []; rows = rows.filter(function (r) { return fs.every(function (f) { var actual = r[String(f.field).toLowerCase()]; return String(actual == null ? '' : actual).trim().toLowerCase() === String(f.value == null ? '' : f.value).trim().toLowerCase(); }); }); return { records: rows.map(function (r) { return { data: systemRecordData_(r), meta: r._meta || {} }; }), nextCursor: null }; }, queryAll: function (t, o) { return this.query(t, o || {}); }, create: function (t, d, o) { var sheet = getSheet_(t, CONFIG.AUTH_SPREADSHEET_ID), headers = getHeaders_(sheet), id = o && o.documentId ? o.documentId : getNextId_(CONFIG.AUTH_SPREADSHEET_ID, t), values = headers.map(function (h) { var k = String(h).trim(); return k.toLowerCase() === 'id' ? id : (d[k] !== undefined ? d[k] : (d[k.toLowerCase()] !== undefined ? d[k.toLowerCase()] : '')); }); sheet.appendRow(values); noteMutation_(sheet); var rec = {}; headers.forEach(function (h, i) { rec[String(h).trim().toLowerCase()] = values[i]; }); return { data: rec, meta: { documentId: String(sheet.getLastRow()), updateTime: '' } }; }, patch: function (t, id, d) { var sheet = getSheet_(t, CONFIG.AUTH_SPREADSHEET_ID), row = Number(id); if (!isFinite(row) || row < 2 || row !== Math.floor(row) || row > sheet.getLastRow()) throw new Error('STORAGE_NOT_FOUND: ' + t + '/' + id); var headers = getHeaders_(sheet), current = sheet.getRange(row, 1, 1, headers.length).getValues()[0], next = current.map(function (value, index) { var key = String(headers[index]).trim().toLowerCase(), found = Object.keys(d || {}).find(function (k) { return String(k).trim().toLowerCase() === key; }); return found === undefined ? value : d[found]; }); sheet.getRange(row, 1, 1, next.length).setValues([next]); noteMutation_(sheet); var rec = {}; headers.forEach(function (h, i) { rec[String(h).trim().toLowerCase()] = next[i]; }); return { data: rec, meta: { documentId: String(row), updateTime: '' } }; }, remove: function (t, id) { var sheet = getSheet_(t, CONFIG.AUTH_SPREADSHEET_ID), row = Number(id); if (!isFinite(row) || row < 2 || row !== Math.floor(row) || row > sheet.getLastRow()) throw new Error('STORAGE_NOT_FOUND: ' + t + '/' + id); sheet.deleteRow(row); noteMutation_(sheet); return true; } }; }
function firestoreStore_(c) { return { query: function (t, o) { var r = firestoreQueryDocuments_(c, systemSchema_(t).collection, o || {}); return { records: r.records, nextCursor: r.nextCursor }; }, queryAll: function (t, o) { var opts = o || {}, out = [], cursor = opts.cursor || null, pages = 0; do { var p = this.query(t, Object.assign({}, opts, { cursor: cursor, limit: opts.limit || FIRESTORE_PAGE_SIZE_ })); out = out.concat(p.records); cursor = p.nextCursor; if (++pages > 1000) throw new Error('STORAGE_LIMIT_ERROR: pagination exceeded 250000 records'); } while (cursor); return { records: out, nextCursor: null }; }, create: function (t, d, o) { var r = firestoreCreateDocument_(c, systemSchema_(t).collection, d, o || {}); return { data: r.data, meta: r.meta }; }, patch: function (t, id, d, o) { var r = firestorePatchDocument_(c, systemSchema_(t).collection, id, d, o || {}); return { data: r.data, meta: r.meta }; }, remove: function (t, id, o) { return firestoreDeleteDocument_(c, systemSchema_(t).collection, id, o || {}); }, transact: function (writes) { var encoded = (writes || []).map(function (w) { var s = systemSchema_(w.tableName); return { update: { name: 'projects/' + c.projectId + '/databases/' + c.databaseId + '/documents/' + s.collection + '/' + w.documentId, fields: firestoreEncodeFields_(w.data || {}) }, updateMask: { fieldPaths: Object.keys(w.data || {}).map(firestoreQuoteFieldPath_) } }; }); return firestoreCommit_(c, encoded); } }; }
