/**
 * Page_Boot_Reads.js — GENERATED by `node tools/pageboot/gen_reads.js --wave 3`
 * from tools/pageboot/inventory.json. DO NOT EDIT BY HAND: change the
 * inventory (or waves.json / overrides.json) and generate again.
 *
 * page action -> { company, reads: [{ action, data }], waitFor? }. Code.js
 * pageBootInject_ runs these reads while doGet renders the page and embeds
 * the replies; Client_Helpers API.call answers the matching first call from
 * them. A page not listed here is not touched at all.
 * 49 page(s).
 */
var PAGE_BOOT_READS = {
  "et_dashboard": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_dashboard_data","data":{}}]},
  "et_kpi": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_kpi_data","data":{}}]},
  "et_analysis_review": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_dashboard_data","data":{}}]},
  "et_products": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_products"}},{"action":"get_et_products","data":{"skipStock":true}}],"waitFor":"stock"},
  "et_categories": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_categories"}},{"action":"get_et_categories","data":{}}]},
  "et_customers": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_customers"}},{"action":"get_et_parties","data":{"direction":"","skipBalances":true}}],"waitFor":"balances"},
  "et_purchasing": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_purchasing"}},{"action":"get_et_purchasing_headers","data":{}}]},
  "et_purchase_print": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_purchase_print","data":{"purchase_code":"$param:purchase_code"}}]},
  "et_sales": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_sales"}},{"action":"get_et_sales_headers","data":{}}]},
  "et_sales_offer": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_sales_offer"}},{"action":"get_et_sales_offer_headers","data":{}}]},
  "et_sales_print": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_sales_print","data":{"sales_code":"$param:purchase_code"}}]},
  "et_sales_costing_print": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_sales_costing","data":{"sales_code":"$param:purchase_code"}}]},
  "et_sales_release": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_sales_print","data":{"sales_code":"$param:purchase_code"}}]},
  "et_sales_returns": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_sales_returns","data":{"invoice_id":"$param:purchase_code"}}]},
  "et_sales_offer_print": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_sales_offer_print","data":{"offer_code":"$param:purchase_code"}}]},
  "et_sales_analysis": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_sales_analysis","data":{"date_from":"","date_to":"","customer_id":"","product_id":""}}]},
  "et_sales_costing_analysis": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_sales_costing_analysis","data":{"date_from":"","date_to":""}}]},
  "et_income_statement": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_income_statement","data":{"date_from":"","date_to":""}}]},
  "et_financial_position": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_financial_position","data":{"date_from":"","date_to":"","recalc_running":false}}]},
  "et_cash": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_cash_headers","data":{"loadAll":true}}]},
  "et_cash_report": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_cash_report","data":{"date_from":"","date_to":"","box":"","type":""}}]},
  "et_customer_statement": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_customer_statement","data":{"customer_id":"$param:purchase_code","date_from":"","date_to":""}}]},
  "et_purchase_needs": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_purchase_needs","data":{}}]},
  "et_product_movement": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_product_movement","data":{"product_id":"$param:purchase_code","date_from":"","date_to":""}}]},
  "et_manufacture": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_manufacture"}},{"action":"get_et_manufacture_headers","data":{}}]},
  "et_manufacture_print": {"company":"37fc50edf1424abd","reads":[{"action":"get_et_manufacture_print","data":{"mo_code":"$param:mo_code"}}]},
  "tl_dashboard": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_dashboard_data","data":{}}]},
  "tl_kpi": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_kpi_data","data":{}}]},
  "tl_analysis_review": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_dashboard_data","data":{}}]},
  "tl_products": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_page_versions","data":{"page":"tl_products"}},{"action":"get_products","data":{}}]},
  "tl_customers": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_page_versions","data":{"page":"tl_customers"}},{"action":"get_parties","data":{"direction":""}}]},
  "tl_purchasing": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_page_versions","data":{"page":"tl_purchasing"}},{"action":"get_purchasing_headers","data":{}}]},
  "tl_purchase_print": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_purchase_print","data":{"purchase_code":"$param:purchase_code"}}]},
  "tl_sales": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_page_versions","data":{"page":"tl_sales"}},{"action":"get_sales_headers","data":{}}]},
  "tl_sales_offer": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_page_versions","data":{"page":"tl_sales_offer"}},{"action":"get_sales_offer_headers","data":{}}]},
  "tl_sales_print": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_sales_print","data":{"sales_code":"$param:purchase_code"}}]},
  "tl_sales_costing_print": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_sales_costing","data":{"sales_code":"$param:purchase_code"}}]},
  "tl_sales_release": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_sales_print","data":{"sales_code":"$param:purchase_code"}}]},
  "tl_sales_returns": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_sales_returns","data":{"invoice_id":"$param:purchase_code"}}]},
  "tl_sales_offer_print": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_sales_offer_print","data":{"offer_code":"$param:purchase_code"}}]},
  "tl_sales_analysis": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_sales_analysis","data":{"date_from":"","date_to":"","customer_id":"","product_id":""}}]},
  "tl_sales_costing_analysis": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_sales_costing_analysis","data":{"date_from":"","date_to":""}}]},
  "tl_income_statement": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_income_statement","data":{"date_from":"","date_to":""}}]},
  "tl_financial_position": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_financial_position","data":{"date_from":"","date_to":"","recalc_running":false}}]},
  "tl_cash": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_cash_headers","data":{"loadAll":true}}]},
  "tl_cash_report": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_cash_report","data":{"date_from":"","date_to":"","box":"","type":""}}]},
  "tl_customer_statement": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_customer_statement","data":{"customer_id":"$param:purchase_code","date_from":"","date_to":""}}]},
  "tl_purchase_needs": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_purchase_needs","data":{}}]},
  "tl_product_movement": {"company":"8df5c89a117fe9a5","reads":[{"action":"get_product_movement","data":{"product_id":"$param:purchase_code","date_from":"","date_to":""}}]}
};
