/**
 * Page_Boot_Reads.js — GENERATED by `node tools/pageboot/gen_reads.js --wave 1`
 * from tools/pageboot/inventory.json. DO NOT EDIT BY HAND: change the
 * inventory (or waves.json / overrides.json) and generate again.
 *
 * page action -> { company, reads: [{ action, data }], waitFor? }. Code.js
 * pageBootInject_ runs these reads while doGet renders the page and embeds
 * the replies; Client_Helpers API.call answers the matching first call from
 * them. A page not listed here is not touched at all.
 * 2 page(s).
 */
var PAGE_BOOT_READS = {
  "et_products": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_products"}},{"action":"get_et_products","data":{"skipStock":true}}],"waitFor":"stock"},
  "et_customers": {"company":"37fc50edf1424abd","reads":[{"action":"get_page_versions","data":{"page":"et_customers"}},{"action":"get_et_parties","data":{"direction":"","skipBalances":true}}],"waitFor":"balances"}
};
