/**
 * Writes Page_Boot_Reads.js — the PAGE_BOOT_READS map Code.js pageBootInject_
 * reads — from tools/pageboot/inventory.json, for the pages switched on in
 * waves 1..N of tools/pageboot/waves.json. Only pages whose decision is BOOT
 * are ever written.
 *
 *   node tools/pageboot/gen_reads.js --wave N     (N = 0 writes an empty map)
 *
 * Deterministic: the same inventory and wave always produce the same bytes.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const arg = process.argv.indexOf('--wave');
const wave = arg === -1 ? NaN : Number(process.argv[arg + 1]);
if (!Number.isInteger(wave) || wave < 0) {
  console.error('usage: node tools/pageboot/gen_reads.js --wave N   (N >= 0)');
  process.exit(2);
}

const inv = JSON.parse(fs.readFileSync(path.join(__dirname, 'inventory.json'), 'utf8'));
const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'waves.json'), 'utf8'));
const waveKeys = Object.keys(cfg.waves).map(Number).sort((a, b) => a - b);
if (wave > waveKeys[waveKeys.length - 1]) { console.error('no wave ' + wave + ' in waves.json'); process.exit(2); }

const chosen = new Set();
waveKeys.filter(k => k <= wave).forEach(function (k) {
  const w = cfg.waves[String(k)];
  inv.pages.forEach(function (p) {
    if (p.decision !== 'BOOT') return;
    if ((w.pages || []).indexOf(p.action) !== -1 || (w.companies || []).indexOf(p.company) !== -1) chosen.add(p.action);
  });
});

const rows = inv.pages.filter(p => chosen.has(p.action));
const lines = rows.map(function (p) {
  const spec = { company: p.uid, reads: p.boot };
  if (cfg.waitFor && cfg.waitFor[p.action]) spec.waitFor = cfg.waitFor[p.action];
  return '  ' + JSON.stringify(p.action) + ': ' + JSON.stringify(spec);
});

const eol = fs.readFileSync(path.join(ROOT, 'Code.js'), 'utf8').indexOf('\r\n') !== -1 ? '\r\n' : '\n';
const text = [
  '/**',
  ' * Page_Boot_Reads.js — GENERATED by `node tools/pageboot/gen_reads.js --wave ' + wave + '`',
  ' * from tools/pageboot/inventory.json. DO NOT EDIT BY HAND: change the',
  ' * inventory (or waves.json / overrides.json) and generate again.',
  ' *',
  ' * page action -> { company, reads: [{ action, data }], waitFor? }. Code.js',
  ' * pageBootInject_ runs these reads while doGet renders the page and embeds',
  ' * the replies; Client_Helpers API.call answers the matching first call from',
  ' * them. A page not listed here is not touched at all.',
  ' * ' + rows.length + ' page(s).',
  ' */',
  'var PAGE_BOOT_READS = {',
  lines.join(',' + eol),
  '};',
  ''
].join(eol).replace(eol + eol + '};', eol + '};');

fs.writeFileSync(path.join(ROOT, 'Page_Boot_Reads.js'), text);
console.log('Page_Boot_Reads.js: wave ' + wave + ', ' + rows.length + ' page(s)');
