  /* [live-notice] PAGE_VIEWS:begin — generated by tools/liveviews/gen_page_views.js from tools/liveviews/inventory.json; edit there. */
  /**
   * [live-notice D2] What each VIEW of a page shows: every table whose data is
   * visible there, including tables that only supply a name, a total or an
   * available quantity. The reason for each table is in tools/liveviews/inventory.md.
   * get_page_versions watches PAGE_TABLES ∪ these, and tells the page which view
   * each moved table belongs to, so a change off-screen does not interrupt.
   */
  const TABLE_LABELS = (function () {
    const o = {};
    o[BOX_SHEET] = 'أكواد الصناديق';
    o[CASH_SHEET] = 'حركة النقدية';
    o[CATEGORIES_SHEET] = 'التصنيفات';
    o[CHART_SHEET] = 'دليل الحسابات';
    o[CURRENT_PRODUCTS_SHEET] = 'أرصدة المخزون';
    o[CUSTOMERS_SHEET] = 'العملاء والموردون';
    o[MFG_LINES_SHEET] = 'أصناف التصنيع';
    o[MFG_SHEET] = 'التصنيع';
    o[PURCHASING_LINES_SHEET] = 'أصناف المشتريات';
    o[PRODUCTS_SHEET] = 'المنتجات';
    o[PURCHASING_SHEET] = 'المشتريات';
    o[SALES_SHEET] = 'المبيعات';
    o[OFFER_SHEET] = 'عروض الأسعار';
    o[OFFER_LINES_SHEET] = 'أصناف عروض الأسعار';
    o[SALES_LINES_SHEET] = 'أصناف المبيعات';
    o[SALES_RETURNS_SHEET] = 'مرتجعات المبيعات';
    return o;
  })();
  const PAGE_VIEWS = {
    'et_cash': {
      'list': [CASH_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, BOX_SHEET, CUSTOMERS_SHEET, CHART_SHEET]
    },
    'et_customers': {
      'list': [CUSTOMERS_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, PURCHASING_SHEET, SALES_SHEET, CASH_SHEET]
    },
    'et_manufacture': {
      'list': [MFG_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, PRODUCTS_SHEET, MFG_LINES_SHEET],
      'form': [MFG_LINES_SHEET, PRODUCTS_SHEET, CURRENT_PRODUCTS_SHEET, MFG_SHEET, PURCHASING_LINES_SHEET]
    },
    'et_products': {
      'list': [PRODUCTS_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, CATEGORIES_SHEET, CHART_SHEET]
    },
    'et_purchasing': {
      'list': [PURCHASING_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, CUSTOMERS_SHEET, PRODUCTS_SHEET, CHART_SHEET],
      'form': [PURCHASING_LINES_SHEET, PRODUCTS_SHEET, CURRENT_PRODUCTS_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, PURCHASING_SHEET, CUSTOMERS_SHEET, CHART_SHEET]
    },
    'et_sales': {
      'list': [SALES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, CUSTOMERS_SHEET, PRODUCTS_SHEET],
      'form': [SALES_LINES_SHEET, PRODUCTS_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_RETURNS_SHEET, SALES_SHEET, CUSTOMERS_SHEET]
    },
    'et_sales_offer': {
      'list': [OFFER_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET, CUSTOMERS_SHEET, PRODUCTS_SHEET],
      'form': [OFFER_LINES_SHEET, PRODUCTS_SHEET, CURRENT_PRODUCTS_SHEET, PURCHASING_LINES_SHEET, SALES_LINES_SHEET, SALES_RETURNS_SHEET]
    }
  };
  /* [live-notice] PAGE_VIEWS:end */
